### ISSUE TITLE
关于添加附件的问题

### ISSUE THREAD

**Issue by kiwiflydream** [SunnyMarkLiu/emailutil#1]
你好！
  请问，添加附件时，可以像网页端一样可以直接添加163网盘里面的文件吗？

**Comment by SunnyMarkLiu** [comment]
不好意思，这个功能不能直接实现，因为从 JavaMail 中添加附件的类`FileDataSource`中只有：
`public FileDataSource(File file)`和`public FileDataSource(String name)`两种类型的构造函数，没有类似于`public FileDataSource(InputStream in)`类型的。可以考虑通过先把163网盘的文件下载到本地，再设置附件。163邮箱的那个功能我觉得也是类似的。

**Comment by SunnyMarkLiu** [comment]
可以继承`FileDataSource`，扩展`FileDataSource`的功能，实现可以添加网络上的资源作为附件。

**Comment by kiwiflydream** [comment]
好的，谢谢你的回答，我试一下，(*´∀`)~♥

**Comment by kiwiflydream** [comment]
JavaMail有一个现成的 URLDataSource，可以实现类似功能：

[[JavaMail]11 详解附件和DataHandler、DataSource](http://blog.sina.com.cn/s/blog_6d3c1ec601010u3n.html)
[javamail mail image located on remote machine](http://stackoverflow.com/questions/6524468/javamail-mail-image-located-on-remote-machine)
``` java
BodyPart imagen = new MimeBodyPart(); 

URL url = new URL("http://server.com/mybestpicture.jpg");
URLDataSource ds = new URLDataSource(url); 
image.setDataHandler(new DataHandler(ds)); 

image.setHeader("Content-ID", "img");
```
